### ISSUE TITLE
change texture of elevator

### ISSUE THREAD

**Issue by FreshDoktor** [Aton-Kish/quartz-elevator#38]
### Describe the solution you'd like

It would be nice if you can change the texture of the elevator to any block 

### Additional context

The elevator would be more fitting in the floor of the buildings

**Comment by Aton-Kish** [comment]
I have no plans to enable to change textures because this is the "Quartz" Elevator.

If you really want to change the textures, you can manually modify the model files.
<https://minecraft.fandom.com/wiki/Model>
```text
quartz-elevator.jar
└── assets
        └── quartzelv
                └── models
                        ├── block
                        │       ├── smooth_quartz_elevator.json  <- edit
                        │       └── quartz_elevator.json  <- edit
                        └── item
                                 ├── smooth_quartz_elevator.json  <- edit
                                 └── quartz_elevator.json  <- edit
```

If you're bothered by particles, you can hide them. (ModMenu > Quartz Elvator > Display particles: Yes -> No)
![](https://user-images.githubusercontent.com/38515249/150368987-97a06751-570b-4534-bdf5-8d55da31f6fe.png)
